<a href="https://colab.research.google.com/github/paladugulashruthi/assignment-no-2/blob/main/Assignment_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#convert the above paragraph into vector using
'''1.Word2vec
2.USE
3.ELMO
4.GP2
5.Sentence-BERT'''

'1.Word2vec\n2.USE\n3.ELMO\n4.GP2\n5.Sentence-BERT'

In [ ]:
my_string='''A paragraph is a series of sentences that are organized and coherent, and are 
all  related  to  a  single  topic.  Almost  every  piece  of  writing  you  do  that  is 
longer  than  a  few  sentences  should  be  organized  into  paragraphs.  This  is 
because paragraphs show a reader where the subdivisions of an essay begin 
and end, and thus help the reader see the organization of the essay and grasp 
its main points.
Paragraphs  can  contain  many  different  kinds  of  information.  A  paragraph 
could  contain  a  series  of  brief  examples  or  a  single  long  illustration  of  a 
general  point.  It  might  describe  a  place,  character,  or  process;  narrate  a 
series of events; compare or contrast two or more things; classify items into 
categories;  or  describe  causes  and  effects.  Regardless  of  the  kind  of 
information they contain, all paragraphs share certain characteristics. One 
of the most important of these is a topic sentence.'''

In [ ]:
print(my_string)

A paragraph is a series of sentences that are organized and coherent, and are 
all  related  to  a  single  topic.  Almost  every  piece  of  writing  you  do  that  is 
longer  than  a  few  sentences  should  be  organized  into  paragraphs.  This  is 
because paragraphs show a reader where the subdivisions of an essay begin 
and end, and thus help the reader see the organization of the essay and grasp 
its main points.
Paragraphs  can  contain  many  different  kinds  of  information.  A  paragraph 
could  contain  a  series  of  brief  examples  or  a  single  long  illustration  of  a 
general  point.  It  might  describe  a  place,  character,  or  process;  narrate  a 
series of events; compare or contrast two or more things; classify items into 
categories;  or  describe  causes  and  effects.  Regardless  of  the  kind  of 
information they contain, all paragraphs share certain characteristics. One 
of the most important of these is a topic sentence.


In [ ]:
import numpy as np
import re
import nltk
import gensim
from nltk.corpus import stopwords
from gensim.models import word2vec
from nltk.tokenize import PunktSentenceTokenizer
nltk.download('punkt')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


True

In [ ]:
#1.word2vec
#code to convert paragraph to sentences
def essay_to_sentences(paragraph):
    tokenizer = nltk.data.load('tokenizers/punkt/english.pickle')
    raw_sentences = tokenizer.tokenize(paragraph.strip())
    sentences = []
    for raw_sentence in raw_sentences:
        if len(raw_sentence) > 0:
            sentences.append((raw_sentence))
    return sentences

sentences=essay_to_sentences(my_string)

sentences

['A paragraph is a series of sentences that are organized and coherent, and are \nall  related  to  a  single  topic.',
 'Almost  every  piece  of  writing  you  do  that  is \nlonger  than  a  few  sentences  should  be  organized  into  paragraphs.',
 'This  is \nbecause paragraphs show a reader where the subdivisions of an essay begin \nand end, and thus help the reader see the organization of the essay and grasp \nits main points.',
 'Paragraphs  can  contain  many  different  kinds  of  information.',
 'A  paragraph \ncould  contain  a  series  of  brief  examples  or  a  single  long  illustration  of  a \ngeneral  point.',
 'It  might  describe  a  place,  character,  or  process;  narrate  a \nseries of events; compare or contrast two or more things; classify items into \ncategories;  or  describe  causes  and  effects.',
 'Regardless  of  the  kind  of \ninformation they contain, all paragraphs share certain characteristics.',
 'One \nof the most important of these is a topic 

In [ ]:
wordvecs=[nltk.word_tokenize(sent) for sent in sentences]
from nltk.corpus import stopwords
nltk.download('stopwords')
stops=list(set(stopwords.words("english")))


for i in wordvecs:
  for j in i:
    if j in stops:
      i.remove(j)
    elif len(j)==1:
      i.remove(j)

model=gensim.models.Word2Vec(wordvecs,min_count=1,size=32)

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


In [ ]:
#printing vector form of word 'paragraph'
model['paragraph']

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: DeprecationWarning: Call to deprecated `__getitem__` (Method will be removed in 4.0.0, use self.wv.__getitem__() instead).
  


array([-0.00811625,  0.00884097, -0.00621052, -0.00251908, -0.00763848,
       -0.00808621,  0.01449601,  0.00411191,  0.00868079,  0.01091974,
        0.00500446, -0.00975691,  0.00850064, -0.01244257, -0.00204979,
       -0.0024896 , -0.00683836,  0.01119102, -0.0028677 ,  0.01098825,
        0.00706284, -0.00153987,  0.00268006,  0.01420962,  0.00200129,
       -0.0098576 ,  0.00103309, -0.01291118,  0.01495626,  0.01113917,
       -0.00792815,  0.00484012], dtype=float32)

In [ ]:
#finding similar words of word 'sentence' in given paragraph
model.most_similar('sentence')

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: DeprecationWarning: Call to deprecated `most_similar` (Method will be removed in 4.0.0, use self.wv.most_similar() instead).
  


[('many', 0.3187304139137268),
 ('longer', 0.3051082491874695),
 ('paragraph', 0.3011867105960846),
 ('long', 0.26626482605934143),
 ('characteristics', 0.2540498375892639),
 ('different', 0.23159722983837128),
 ('compare', 0.1998894065618515),
 ('and', 0.18822717666625977),
 ('thus', 0.18813666701316833),
 ('causes', 0.1625451147556305)]

In [ ]:
#2.USE
import tensorflow_hub as hub
use=hub.load("https://tfhub.dev/google/universal-sentence-encoder/4")
#converting to vectors
embeddings=use(sentences)
print(embeddings)

tf.Tensor(
[[ 0.01419854 -0.01116286  0.06808718 ... -0.08247866 -0.02446434
   0.05483037]
 [ 0.02902018 -0.00415597  0.07664446 ... -0.06830524 -0.00835191
   0.04397805]
 [ 0.06417768 -0.01383496  0.05436629 ... -0.06510986  0.03140234
   0.05601776]
 ...
 [ 0.03035337 -0.04422743  0.05888064 ... -0.06469322  0.03180374
   0.06408841]
 [ 0.0167906   0.00667928  0.01125342 ... -0.01703941  0.00186954
   0.03127917]
 [ 0.00255486 -0.05832284  0.01486255 ... -0.09906971 -0.07840379
   0.06731212]], shape=(8, 512), dtype=float32)


In [ ]:
#3.SENTENCE -BERT
#importing sentencebert model
bert = hub.KerasLayer("https://tfhub.dev/google/nnlm-en-dim128/2")
embeddings2=bert(sentences)
print(embeddings2)

tf.Tensor(
[[ 0.51884556  0.02918336  0.07145058 ...  0.22533715  0.01950222
  -0.1289025 ]
 [ 0.5166956   0.00863559  0.13047293 ...  0.06873029  0.04432377
   0.02298209]
 [ 0.6110389   0.1811815  -0.11061911 ... -0.09788384  0.09358283
   0.07447077]
 ...
 [ 0.39123687 -0.01085754  0.07607286 ...  0.07567259 -0.1484504
  -0.02365224]
 [ 0.24070688 -0.00535227  0.12521958 ... -0.1306146  -0.12194312
   0.00996622]
 [ 0.3799187  -0.05745781  0.09742597 ...  0.0461409  -0.07855327
   0.03973798]], shape=(8, 128), dtype=float32)


In [ ]:
print("shape=",embeddings2[0].shape)
#each sentence is converted into vector having 128 values
print("The sentence: ",sentences[0],"\n is converted as : \n{}".format(embeddings2[0]))
shape= (128,)

shape= (128,)
The sentence:  A paragraph is a series of sentences that are organized and coherent, and are 
all  related  to  a  single  topic. 
 is converted as : 
[ 0.51884556  0.02918336  0.07145058  0.04535037 -0.04259718 -0.1654925
 -0.103632   -0.0106116  -0.19418633  0.18560012  0.05228718 -0.1996645
 -0.08536236  0.03365118 -0.14633818 -0.02451333 -0.07473224  0.0438432
 -0.18141116  0.1372393   0.0136739   0.07080507 -0.00786687 -0.08535285
  0.0715998  -0.06499769 -0.08562539 -0.02720456 -0.05636027 -0.00261944
 -0.01944907 -0.04633158 -0.07786479 -0.16420066 -0.03604371 -0.09477271
  0.05015939 -0.10466915 -0.07002265  0.0187032   0.09759199 -0.08157597
  0.20161884  0.01257148 -0.06885625  0.21009818 -0.01509479 -0.13517898
 -0.09388355  0.01013749 -0.02629396 -0.06578662  0.04543499  0.04652723
  0.10455509  0.05183478  0.10705721 -0.10057095  0.07927544 -0.14144531
 -0.10567372 -0.08833035 -0.07270256 -0.05692196  0.0400563  -0.19360085
 -0.14046225 -0.01617921  0.1345623

In [ ]:
#4.Implementing ELMOS
!pip install "tensorflow>=2.0.0"
!pip install --upgrade tensorflow-hub

In [ ]:
import tensorflow_hub as hub
import tensorflow.compat.v1 as tf
tf.disable_eager_execution()
#1024 sized vectors
elmo=hub.Module("https://tfhub.dev/google/elmo/3",trainable=True)
embeddings=elmo(
    sentences,
    signature="default",
    as_dict=True)["elmo"]
init=tf.initialize_all_variables()
sess=tf.Session()
sess.run(init)
print("\n\n")
print(sess.run(embeddings[0]))
print("shape=",embeddings[0].shape)

INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


Instructions for updating:
Use `tf.global_variables_initializer` instead.


Instructions for updating:
Use `tf.global_variables_initializer` instead.





[[ 0.29286996 -0.14378002 -0.32574052 ... -0.42214906 -0.26807797
  -0.06121337]
 [-0.59441644  0.09640661  0.50537676 ...  0.2956011   0.36285305
   0.46462518]
 [-0.17083307 -0.18744141 -0.27626717 ... -0.6752867   0.36227596
   0.7219782 ]
 ...
 [-0.02840841 -0.04353216  0.04130163 ...  0.02583168 -0.01429836
  -0.01650422]
 [-0.02840841 -0.04353216  0.04130163 ...  0.02583168 -0.01429836
  -0.01650422]
 [-0.02840841 -0.04353216  0.04130163 ...  0.02583168 -0.01429836
  -0.01650422]]
shape= (32, 1024)


In [ ]:
#5.GP2
import torch
!pip install transformers

     |████████████████████████████████| 3.1 MB 5.3 MB/s 
     |████████████████████████████████| 59 kB 4.9 MB/s 
     |████████████████████████████████| 596 kB 59.9 MB/s 
     |████████████████████████████████| 895 kB 63.7 MB/s 
     |████████████████████████████████| 3.3 MB 39.9 MB/s 
  Attempting uninstall: pyyaml
    Found existing installation: PyYAML 3.13
    Uninstalling PyYAML-3.13:
      Successfully uninstalled PyYAML-3.13


In [ ]:
import transformers
gptokenizer=transformers.GPT2Tokenizer.from_pretrained('gpt2-large')
model=transformers.GPT2LMHeadModel.from_pretrained('gpt2-large')
output=gptokenizer.encode(my_string,add_special_tokens=False,return_tensors="pt")
print("shape=",output.shape)
output

Downloading:   0%|          | 0.00/0.99M [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/446k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/1.29M [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/666 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/3.02G [00:00<?, ?B/s]

shape= torch.Size([1, 264])


tensor([[   32,  7322,   318,   257,  2168,   286, 13439,   326,   389,  8389,
           290, 24870,    11,   290,   389,   220,   198,   439,   220,  3519,
           220,   284,   220,   257,   220,  2060,   220,  7243,    13,   220,
         16699,   220,   790,   220,  3704,   220,   286,   220,  3597,   220,
           345,   220,   466,   220,   326,   220,   318,   220,   198,  6511,
           263,   220,   621,   220,   257,   220,  1178,   220, 13439,   220,
           815,   220,   307,   220,  8389,   220,   656,   220, 23549,    13,
           220,   770,   220,   318,   220,   198, 13893, 23549,   905,   257,
          9173,   810,   262, 45944,  3279,   286,   281, 14268,  2221,   220,
           198,   392,   886,    11,   290,  4145,  1037,   262,  9173,   766,
           262,  4009,   286,   262, 14268,   290, 13180,   220,   198,   896,
          1388,  2173,    13,   198, 10044,  6111,    82,   220,   460,   220,
          3994,   220,   867,   220,  1180,   220,  

In [ ]:
#2
import spacy
from spacy import displacy
ner=spacy.load('en')
result=ner(my_string)

for word in result.ents:
  print(word.text,word.label_)

two CARDINAL
One CARDINAL


In [ ]:
spacy.explain('GPE')

'Countries, cities, states'

In [ ]:
#better visualisation of entity recognition
displacy.render(result,style="ent",jupyter=True)

In [ ]:
# finding named entities of another paragraph
resultss=ner("Cricket was introduced to India by British sailors in the 18th century, and the first cricket club was established in 1792. India's national cricket team did not play its first Test match until 25 June 1932 at Lord's, becoming the sixth team to be granted test cricket status. From 1932 India had to wait until 1952, almost 20 years for its first Test victory. In its first fifty years of international cricket, India didn't gain much success, winning only 35 of the first 196 Test matches it played. The team, however, gained strength in the 1970s with the emergence of players like Gavaskar, Viswanath, Kapil Dev, and the Indian spin quartet.")
for word in resultss.ents:
  print(word.text,word.label_)

India GPE
British NORP
the 18th century DATE
first ORDINAL
1792 DATE
India GPE
first ORDINAL
25 June 1932 DATE
sixth ORDINAL
1932 DATE
India GPE
1952 DATE
almost 20 years DATE
first ORDINAL
its first fifty years DATE
India GPE
only 35 CARDINAL
first ORDINAL
196 CARDINAL
the 1970s DATE
Gavaskar PERSON
Viswanath ORG
Kapil Dev PERSON
Indian NORP


In [ ]:
#better visualisation of entity recognition
displacy.render(resultss,style="ent",jupyter=True)

In [ ]:
pip install -U sentence-transformers

     |████████████████████████████████| 78 kB 3.5 MB/s 
     |████████████████████████████████| 1.2 MB 11.7 MB/s 
  Created wheel for sentence-transformers: filename=sentence_transformers-2.1.0-py3-none-any.whl size=121000 sha256=6026a1a42aeb8e5953beae219e0d430d300e1eb8eea2004c67eef9028d8e598d
  Stored in directory: /root/.cache/pip/wheels/90/f0/bb/ed1add84da70092ea526466eadc2bfb197c4bcb8d4fa5f7bad
Successfully built sentence-transformers


In [ ]:
from sentence_transformers import SentenceTransformer
sbert_model = SentenceTransformer('bert-base-nli-mean-tokens')

Downloading:   0%|          | 0.00/391 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/3.95k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/2.00 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/625 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/122 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/229 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/438M [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/112 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/466k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/399 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/232k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/190 [00:00<?, ?B/s]

In [ ]:
se_embeddings = sbert_model.encode(sentences)
q1_vec= sbert_model.encode(sentences[0])

#cosine similarity function
#identifies similarity between 2 sentences
def cosine(u, v):
    return np.dot(u, v) / (np.linalg.norm(u) * np.linalg.norm(v))

for sent in sentences:
  sim = cosine(q1_vec, sbert_model.encode([sent])[0])
  #if similarity ==1 => repeated sentence
  #if similarity > 0.6 => similar sentence
  if sim>0.6:
    print("Sentence1 =",sentences[0],"\n \nSentence2=", sent, "\n\nsimilarity = ", sim,end="\n ----------------------------- \n")

Sentence1 = A paragraph is a series of sentences that are organized and coherent, and are 
all  related  to  a  single  topic. 
 
Sentence2= A paragraph is a series of sentences that are organized and coherent, and are 
all  related  to  a  single  topic. 

similarity =  1.0
 ----------------------------- 
Sentence1 = A paragraph is a series of sentences that are organized and coherent, and are 
all  related  to  a  single  topic. 
 
Sentence2= Almost  every  piece  of  writing  you  do  that  is 
longer  than  a  few  sentences  should  be  organized  into  paragraphs. 

similarity =  0.64775366
 ----------------------------- 
Sentence1 = A paragraph is a series of sentences that are organized and coherent, and are 
all  related  to  a  single  topic. 
 
Sentence2= A  paragraph 
could  contain  a  series  of  brief  examples  or  a  single  long  illustration  of  a 
general  point. 

similarity =  0.6927288
 ----------------------------- 
Sentence1 = A paragraph is a series of senten

In [ ]:
#4. Explain POS tagging with HMM?


Parts of Speech Tagging (POS): It is a process of converting a sentence to forms – list of words, list of tuples (where each tuple is having a form (word, tag)). The tag in case of is a part-of-speech tag, and signifies whether the word is a noun, adjective, verb, and so on. reading a sentence and being able to identify what words act as nouns, pronouns, verbs, adverbs, and so on. All these are referred to as the part of speech tags.   According to Wikipedia, part-of-speech tagging (POS tagging or PoS tagging or POST), also called grammatical tagging or word-category disambiguation, is the process of marking up a word in a text as corresponding to a particular part of speech, based on both its definition and its context i.e. its relationship with adjacent and related words in a phrase, sentence, or paragraph.

Default tagging is a basic step for the part-of-speech tagging. It is performed using the DefaultTagger class. The DefaultTagger class takes ‘tag’ as a single argument. NN is the tag for a singular noun. DefaultTagger is most useful when it gets to work with most common part-of-speech tag. that’s why a noun tag is recommended.

POS tagging with Hidden Markov Model HMM (Hidden Markov Model) is a Stochastic technique for POS tagging. Hidden Markov models are known for their applications to reinforcement learning and temporal pattern recognition such as speech, handwriting, gesture recognition, musical score following, partial discharges, and bioinformatics.